RESOURCES_PATH = './Resources'
MEMES_PATH = '{}{}'.format(RESOURCES_PATH, '/Memes')
REACTIONS_PATH = '{}{}'.format(RESOURCES_PATH, '/Reactions')
HOT_TAKES_PATH = '{}{}'.format(RESOURCES_PATH, '/Hottakes')
QUOTES_PATH = '{}{}'.format(RESOURCES_PATH, '/quote_df.csv')
WIN_SLIPS_PATH = '{}{}'.format(REACTIONS_PATH, '/win.jpg')
ELON_PATH = '{}{}'.format(RESOURCES_PATH, '/Elon.csv')
DOG_PATH = '{}{}'.format(RESOURCES_PATH, '/Dogs')
CAT_PATH = '{}{}'.format(RESOURCES_PATH, '/Cats')